from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'index.html', views.index, name='index'),
    url(r'page1.html/', views.page1, name='page1'),
    url(r'page2.html', views.page2, name='page2'),
    url(r'page3.html', views.page3, name='page3'),
    url(r'page4.html', views.page4, name='page4'),
    url(r'page5.html', views.page5, name='page5'),
    url(r'page14.html', views.page14, name='page14'),
    url(r'page6.html', views.page6, name='page6'),
    url(r'page7.html', views.page7, name='page7'),
    url(r'page8.html', views.page8, name='page8'),
    url(r'page9.html', views.page9, name='page9'),
    url(r'page10.html', views.page10, name='page10'),
    url(r'page11.html', views.page11, name='page11'),
    url(r'page12.html', views.page12, name='page12'),
    url(r'page15.html', views.page15, name='page15'),
    url(r'page16.html', views.page16, name='page16'),
    url(r'page17.html', views.page17, name='page17'),
    url(r'page18.html', views.page18, name='page18'),
    url(r'page19.html', views.page19, name='page19'),
    url(r'page13.html', views.page13, name='page13'),
    url(r'page20.html', views.page20, name='page20'),
    url(r'page21.html', views.page21, name='page21'),
    url(r'page22.html', views.page22, name='page22'),
    url(r'page23.html', views.page23, name='page23'),
    url(r'page24.html', views.page24, name='page24'),
    url(r'page25.html', views.page25, name='page25'),
    url(r'page26.html', views.page26, name='page26'),
    url(r'page27.html', views.page27, name='page27'),
    url(r'page28.html', views.page28, name='page28'),
    url(r'page29.html', views.page29, name='page29'),
    url(r'page30.html', views.page30, name='page30'),
    url(r'page31.html', views.page31, name='page31'),
    url(r'page32.html', views.page32, name='page32'),
    url(r'page33.html', views.page33, name='page33'),
    url(r'page34.html', views.page34, name='page34'),
    url(r'page35.html', views.page35, name='page35'),
    url(r'page36.html', views.page36, name='page36'),
    url(r'ad1.html', views.ad1, name='ad1'),
    url(r'ad2.html', views.ad2, name='ad2'),
]
